### ISSUE TITLE
What features will you app provide?

### ISSUE THREAD

**Issue by m-ashraf-cs** [ezaz-ahamed/212CSE499.12#1]
List the features you want to offer through your app. Also, try to mention the difficulty of implementing the features.

**Comment by ezaz-ahamed** [comment]
# Feature Set

 - **Real-time location tracking**
 
Users (driver) can see their real time location within the app and navigate to a nearby available parking spot with GPS integration.

 - **Real-time parking spot availability**

View real-time availability and information on local restrictions, book a guaranteed space in seconds.

 - **Free service**

Basic parking service available with real-time spot availability checking. Real time parking spot availability checking. Adequate and easy to access parking locations.

 - **Premium service**

Extra benefits in addition to the basic parking services, including real time updates, extra security features and better locations, reminders.

 - **Parking spot reservation**

Search for where you want to park and select the specific parking facility. Choose the date/time and complete your reservation.

 - **Multiple payment system**

Make payments using digital payment services and cash (location dependent availability). In app credits can be used for more convenient payment options.

 - **Share own parking space**


Building owners can make their parking spots available through the app and get additional revenue.

 - **Spot availability prediction**


Users can get predicted parking spot availability for a different time if they do not want to reserve location for future use.

 - **Accessibility first**

The app will be designed with accessibility in mind for all types of users. The app will provide voice feedback for in-app functionality for easy use during driving.

Difficulty and the sequence of feature implementation can be followed in the invited trello board.
